// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmrGoWdouQfzHz3ToGdaLv8HXRATphrZU',
    appId: '1:950834867722:web:1c0458713b9e93447a39f3',
    messagingSenderId: '950834867722',
    projectId: 'alerton-f8f71',
    authDomain: 'alerton-f8f71.firebaseapp.com',
    storageBucket: 'alerton-f8f71.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCi9CdP_ION6TH8V_BHm2Vros7nccL_xE',
    appId: '1:950834867722:android:c5e438a68b63175a7a39f3',
    messagingSenderId: '950834867722',
    projectId: 'alerton-f8f71',
    storageBucket: 'alerton-f8f71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_6Nvd8vDy0q8TTegjk3ExbIhIuAVylAE',
    appId: '1:950834867722:ios:b3105c427e59ec6f7a39f3',
    messagingSenderId: '950834867722',
    projectId: 'alerton-f8f71',
    storageBucket: 'alerton-f8f71.firebasestorage.app',
    iosBundleId: 'com.example.weChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_6Nvd8vDy0q8TTegjk3ExbIhIuAVylAE',
    appId: '1:950834867722:ios:b3105c427e59ec6f7a39f3',
    messagingSenderId: '950834867722',
    projectId: 'alerton-f8f71',
    storageBucket: 'alerton-f8f71.firebasestorage.app',
    iosBundleId: 'com.example.weChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmrGoWdouQfzHz3ToGdaLv8HXRATphrZU',
    appId: '1:950834867722:web:62e122ce5d1cbfd67a39f3',
    messagingSenderId: '950834867722',
    projectId: 'alerton-f8f71',
    authDomain: 'alerton-f8f71.firebaseapp.com',
    storageBucket: 'alerton-f8f71.firebasestorage.app',
  );
}
